export const USER_TOKEN = 'user_token'
export const USER_LOGIN = 'user_data'
export const BAKERY_ACCESS_TOKEN = 'bakery_access_token'
export const BAKERY_REFRESH_TOKEN = 'bakery_refresh_token'
export const COOKIE_NET = '.AspNetCore.SharedCookies'
export const COOKIE_CONSENT = 'cookie-consent'
export const LOCALE_COOKIE = 'LOCALE'
