export const USER_TOKEN = 'user_token'
export const USER_LOGIN = 'user_data'
export const SPORTHUB_ACCESS_TOKEN = 'mebi_access_token'
export const SPORTHUB_REFRESH_TOKEN = 'mebi_refresh_token'
export const COOKIE_NET = '.AspNetCore.SharedCookies'
export const COOKIE_CONSENT = 'cookie-consent'
