export const ERROR_CODE = {
    EXPIRED_TOKEN: "EXPIRED_TOKEN",
    INVALID_TOKEN: "INVALID_TOKEN",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
    INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
    ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",
}